/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MyAdjustApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class PhotoGUITest {
    @Test void appHasAGreeting() {
       PhotoGUIp classUnderTest = newPhotoGUIp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
